# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Mod Properties
mod_version=1.0.0
maven_group=com.hoorinekoneko
archives_base_name=vnc-client-mc

# Fabric Properties - Minecraft 1.21.4
# check these on https://fabricmc.net/develop/
minecraft_version=1.21.4
loader_version=0.16.9
loom_version=1.14.3

# Dependencies
fabric_version=0.113.0+1.21.4
